# Generated by Django 5.1.5 on 2025-01-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizar', '0004_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizar.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('PAST', 'Past'), ('TODAY', 'Today')], default='UPCOMING', max_length=20),
        ),
    ]
