# Generated by Django 5.1.5 on 2025-01-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizar', '0005_alter_event_category_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
